[phases.setup]
nixPkgs = ['nodejs-18_x', 'pnpm-8_x', 'ruby_3_2', 'postgresql', 'pkg-config', 'openssl', 'libyaml']

[phases.build]
cmds = [
  'bundle install --deployment --without development test',
  'pnpm install --frozen-lockfile',
  'RAILS_ENV=production SECRET_KEY_BASE=precompile_placeholder bundle exec rake assets:precompile'
]

[variables]
RAILS_ENV = 'production'
RACK_ENV = 'production'
RAILS_LOG_TO_STDOUT = 'enabled'
RAILS_SERVE_STATIC_FILES = 'true'
BUNDLE_WITHOUT = 'development:test'
NODE_OPTIONS = '--max-old-space-size=2048'

[start]
cmd = 'bundle exec rails ip_lookup:setup && bundle exec rails server -p $PORT' 